[package]
name = "solutions"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
tracing = "0.1.40"
tracing-unwrap = "1.0.1"
itertools = "0.14.0"


[lints.clippy]
needless_range_loop = "allow"